// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Railyatri;

#nullable disable

namespace Railyatri.Migrations
{
    [DbContext(typeof(Traindb))]
    [Migration("20220721082423_TrainDb")]
    partial class TrainDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Railyatri.AvailabilitySchedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainNumberid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("TrainNumberid");

                    b.ToTable("AvailabilitySchedule");
                });

            modelBuilder.Entity("Railyatri.TrainSchedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainNumberid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("TrainNumberid");

                    b.ToTable("TrainSchedule");
                });

            modelBuilder.Entity("Railyatri.Trainslist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("FromStation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToStation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainNumber")
                        .HasColumnType("int");

                    b.Property<string>("Trainname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Trainslist");
                });

            modelBuilder.Entity("Railyatri.AvailabilitySchedule", b =>
                {
                    b.HasOne("Railyatri.Trainslist", "TrainNumber")
                        .WithMany()
                        .HasForeignKey("TrainNumberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainNumber");
                });

            modelBuilder.Entity("Railyatri.TrainSchedule", b =>
                {
                    b.HasOne("Railyatri.Trainslist", "TrainNumber")
                        .WithMany()
                        .HasForeignKey("TrainNumberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
